### ISSUE TITLE
Patch ram size

### ISSUE THREAD

**Issue by antisvin** [pingdynasty/OpenWare#10]
There are some inconsistencies in LD scripts for patch RAM size:

1. https://github.com/pingdynasty/OpenWare/blob/master/Hardware/owl2.ld#L12

2. https://github.com/pingdynasty/OpenWare/blob/master/MidiBoot/STM32F427ZI-boot.ld#L12 - looks like leftover value from OWL1

3. The actual value should probably be 192 - 48 = 144kb

Should this be fixed or is there some logic behind this that I don't understand?

**Comment by antisvin** [comment]
And there's sort of related issue in OwlProgram LDscript. It only uses [64k as PATCHRAM section](https://github.com/pingdynasty/OwlProgram/blob/master/Source/flash.ld#L20) (which holds full patch code and data). So it could be extended to either 128k for Owl2 devices with a separate linker script or even to 144k if we utilize all available RAM.

**Comment by pingdynasty** [comment]
Yes correct. It has stayed at 64k simply for historic reasons, and to ensure compatibility with older devices. Been trying to device a way to make it clear to the users what hardware a patch will run on.

**Comment by antisvin** [comment]
Ok, linker script for MidiBoot shouldn't require comptatibility with Owl1 - since it has its own project now. However, it uses RAM section and not PATCHRAM, so my very first comment could be ignored (or linker script could be updated just to make things more logical)

I think I could add a separate linker script for Owl2 devices in OpenWare and a flag to use it instead of legacy compatible script. It can't be used in web patcher until there's device specific build support.

> Been trying to device a way to make it clear to the users what hardware a patch will run on.

If you want to do it when loading patches, that would likely require a different patch format with more info in program header (hardware ID, firmware ID). But determining memory settings used when building patch may already be possible, i.e. by comparing stackEnd - linkAddress in patch header to _PATCHRAM_SIZE.

**Comment by antisvin** [comment]
This has been addressed with changes to linker script.
