### ISSUE TITLE
Minor: Divide by zero warning

### ISSUE THREAD

**Issue by mcclure** [pingdynasty/OpenWare#21]
Built the current develop head efaaa7661bde5349e2996b4974ada9d5b5417b5c. Got these warnings:
```
/mnt/c/Users/Andi/work/gh/OpenWare/Source/Codec.cpp:110:26: warning: division by zero [-Wdiv-by-zero]
   size_t blocksize = len / (USB_AUDIO_CHANNELS*AUDIO_BYTES_PER_SAMPLE);
                      ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/c/Users/Andi/work/gh/OpenWare/Source/Codec.cpp: In function 'void usbd_audio_tx_callback(uint8_t*, size_t)':
/mnt/c/Users/Andi/work/gh/OpenWare/Source/Codec.cpp:147:26: warning: division by zero [-Wdiv-by-zero]
   size_t blocksize = len / (USB_AUDIO_CHANNELS*AUDIO_BYTES_PER_SAMPLE);
                      ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I think this is related to the recent commit labeled "disable USB audio". I would like to suggest if USB_AUDIO_CHANNELS is 0, that should be caught in an #if and this entire section should be omitted, rather than having code that does something nonsensical resulting in a divide by zero.

**Comment by antisvin** [comment]
This is fixed in develop branch as USB code is secured by extra guards, i.e.:
https://github.com/pingdynasty/OpenWare/blob/develop/Source/Codec.cpp#L114

That's besides the fact that USB audio with no channels doesn't seem to work with windows drivers, so we won't be using such configuration.
