### ISSUE TITLE
Owl pedal compatibility?

### ISSUE THREAD

**Issue by shakfu** [pingdynasty/OpenWare#45]
As an owner of the Owl pedal, I've noted that you are making binary firmware releases for your products except for the owl? Is there a reason for this? What the compatibility roadmap for the owl pedal look like?

**Comment by pingdynasty** [comment]
We mostly just need to ensure there's a good upgrade path. The bootloader has changed as well as the firmware, so both will have to be reflashed.
Are you interested in doing some beta testing?

**Comment by shakfu** [comment]
Sure. I'd be happy to provided there's no risk of bricking the unit (-:

**Comment by pingdynasty** [comment]
Answered in #54
